name: Build and Push Runner Omni

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]
    paths:
      - Dockerfile
      - .github/workflows/build-runner-omni.yml
  tags:
    - 'v*.*.*'

env:
  REGISTRY: ghcr.io
  # usa owner/repo automaticamente
  IMAGE_NAME: ${{ github.repository }}-runner-omni

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push (latest + sha)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
